### ISSUE TITLE
Feature Request: Configurable statement timeout

### ISSUE THREAD

**Issue by half0wl** [shayonj/pg_easy_replicate#100]
I'm running into an issue where `CREATE SUBSCRIPTION` times out:

```
PG::QueryCanceled: ERROR:  canceling statement due to statement timeout: CREATE SUBSCRIPTION "pger_subscription_database_cluster_1"
```

I believe setting this higher (10s) should work, but realized that this is hardcoded in https://github.com/shayonj/pg_easy_replicate/blob/fa8fef5605aa220a6723ae198551c344362ddb3f/lib/pg_easy_replicate/query.rb#L18. It'd be great if that value is configurable.

**Comment by shayonj** [comment]
oh! thats such a good idea. Should've done it already. Will get to it this weekend

**Comment by shayonj** [comment]
Out in https://github.com/shayonj/pg_easy_replicate/releases/tag/v0.2.4. Readme updated. 

Thanks for the req.
