### ISSUE TITLE
Docker image does not seem to work on linux/amd64

### ISSUE THREAD

**Issue by pcboy** [shayonj/pg_easy_replicate#14]
```
$ docker run -it --rm shayonj/pg_easy_replicate:latest pg_easy_replicate
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec /usr/local/bundle/bin/pg_easy_replicate: exec format error
```

Seems like it's trying to run an arm version.  

Version:  
Docker version 24.0.2, build cb74dfcd85

I'm on latest Arch Linux on an intel i7 machine.

**Comment by gutleib** [comment]
+
only arm version is published on dockerhub. Can you add at least  linux/amd64 ?

**Comment by shayonj** [comment]
I will take a look at this soon and get the build pipeline going for other platforms

**Comment by shayonj** [comment]
Docker image support for `linux/amd64` and `linux/arm64` is now out starting `0.1.3`. https://hub.docker.com/repository/docker/shayonj/pg_easy_replicate/general

Thanks for report!
