### ISSUE TITLE
Cleanup fails as the source is in readonly mode post switch-over

### ISSUE THREAD

**Issue by RajKiranS** [shayonj/pg_easy_replicate#143]
First of all, great tool! Thanks for this.

Post switch-over, I am trying to run `cleanup` and it fails because the source is in `ReadOnly` mode. Not sure what can be done there though, but we should at least proceed further and do a cleanup on target cluster.

```
$ pg_easy_replicate cleanup --group-name test2 --everything
Unable to cleanup: Unable to drop schema: PG::ReadOnlySqlTransaction: ERROR:  cannot execute DROP SCHEMA in a read-only transaction
```

Appreciate any help.

**Comment by shayonj** [comment]
yeah good call, will look into a fix this weekend.
