### ISSUE TITLE
After sync start, stats seem to be frozen at "initializing" for all subscriptions, no data being transferred.

### ISSUE THREAD

**Issue by joetynan** [shayonj/pg_easy_replicate#177]
Not sure what's going on here. Initiated the sync via the docker container about 18 hours ago, but the status of all the subscriptions is still in "initializing" state.  Config check came back with a green checkmark, and bootstrap was successful.  

For my implementation, I am trying to set up replication between two Azure Postgres Flexible servers.  I did verify that each server's IP is on the whitelist for the other server, just in case there are direct connections between the two for the replication.  I did also notice a public IP under 'client_addr' in the 'lag_stats" output, and added that to the whitelist for both servers as well.

"replication_stats_count_by_state": {
    "initializing": 146
  },
  "message_lsn_receipts": [
    {
      "received_lsn": "E1/C109E828",
      "last_msg_send_time": "2024-11-06 16:00:09 UTC",
      "last_msg_receipt_time": "2024-11-06 16:00:09 UTC",
      "latest_end_lsn": "E1/C109E828",
      "latest_end_time": "2024-11-06 16:00:09 UTC"
    }
  ],
  "sync_started_at": "2024-11-05 23:02:32 UTC",
  "sync_failed_at": null,
  "switchover_completed_at": null
}

**Comment by joetynan** [comment]
for a bit more information, I do see the subscription and publication that pg_easy_replicate configured on the source and target servers, but the subscription on the target server does not include any connection data - no server name, user, etc.

**Comment by joetynan** [comment]
OK, I think this can be closed out now, I do appear to have found the solution.  in azure, the default max workers is 8, which is by far too low, so I had to set it to an arbitrarily high number that was greater than the number of tables being replicated.

**Comment by shayonj** [comment]
ah! yes. That is correct. It would have eventually caught, but I guess would just be super slow. 

Thanks for giving the tool a try, happy to accept any other feedback or help with issues you come across.
