### ISSUE TITLE
Existing Data on target tables question

### ISSUE THREAD

**Issue by joetynan** [shayonj/pg_easy_replicate#178]
I was wondering - if there's existing data in a table, is that data overwritten when replication is established or is existing data left intact?  Curious to see if perhaps I could speed up the initial data copy by doing a dump/restore of larger tables.

**Comment by shayonj** [comment]
`pg_easy_replicate` today doesn't allow the ability to copy & stream today, it just uses postgres Subscription + Publisher so Postgres will try to `COPY` the initial data, so its perhaps better to drop the data. However, few pointers if its useful

- There is a `--recreate-indices-post-copy` flag that drops all the indexes in the target table(s) to make the COPY operation a bit fast, you can try that if you find it useful. It's been a bit hit/miss for me depending on the use case.
- I am also working on a new project [pg_flo](https://github.com/shayonj/pg_flo), that allows you to COPY + stream and the streaming part of the process is resumable. It also performs the COPY in a parallel way, so its fair bit faster as well. In case you find it useful :). It does require NATS today.
