### ISSUE TITLE
Feature Request: leverage connection pooling, is that possible?

### ISSUE THREAD

**Issue by joetynan** [shayonj/pg_easy_replicate#179]
One thing I did notice a bit as I'm experimenting with this is that when I pull up stats and/or check ddl tracking, etc - very often I end up running into _"remaining connection slots are reserved for roles with privileges of the "pg_use_reserved_connections"_ .  Granted, now I know that I need to bump up the number of reserved connections beyond the default, but this is going to add overhead.

**Comment by shayonj** [comment]
Oh thats very interesting, these operations should be be using a single connection (per cli command), max. Are you able to check how many connections are used while the replication is ongoing and also if you don't mind sharing the max connection on the databases? Thank you!

**Comment by joetynan** [comment]
max_connection is set to 1000, however in both azure and AWS, it's not possible to modify the reserved_connections or superuser_connections parameters.  

One thing I think it might be is that, at least in azure, I see a lot of azuresu connections, for whatever reasons.   However, this seems to only pop up when I'm trying to view stats

**Comment by shayonj** [comment]
i see - for stats are you following/tailing it or occasionally using it? Also is there any proxy between pg_easy_replicate and azure?

**Comment by joetynan** [comment]
no proxy that I'm aware of.  Now that the other issue of timeout seems to be resolved, I'll re-attempt to see if this time the configuration is successfully saved on the target server, AND how many slots it's actually using.
