### ISSUE TITLE
Update pg_dump version to latest

### ISSUE THREAD

**Issue by joetynan** [shayonj/pg_easy_replicate#191]
Not sure if this is a reversion or not, but just today I noticed when I try to execute bootstrap on postgres servers running 16.4, I get a pg_dump version mismatch error. Looks like currently the container is using pg_dump 15.9.

**Comment by joetynan** [comment]
doh! should have been more specific-  this is when using the docker image that I get this error.  The "fix" I had was to start an instance of the image and console in, then uninstall postgres-client-15 and install postgres-client-16.

**Comment by shayonj** [comment]
ah! yes, so this is an issue for sure. Because the docker just installs it from the apk repo. Its hard to solve for I guess, since users can be working with different PG versions. Will have to have a think.

**Comment by joetynan** [comment]
one thing that you could try is to update the dockerfile with a couple commands - basically uninstall the old postgres-client-15, and then update/add repo and then install the latest version of the client tools. Just an idea.

**Comment by shayonj** [comment]
yeah, i think thats basically what we might need to do. Because newer clients I _think_ can work with older pg versions (?). Need to check

**Comment by shayonj** [comment]
Fixed https://github.com/shayonj/pg_easy_replicate/releases/tag/v0.3.8
