### ISSUE TITLE
How does pg_easy_replicate manage tables in a publication?

### ISSUE THREAD

**Issue by joetynan** [shayonj/pg_easy_replicate#197]
So, I noticed that if I drop a table from the publication that pg_easy_replicate creates, it actually still shows up when I run the stats command.  And, I see that it's actually getting replicated still.  Does pg_easy_replicate manage the list of tables outside of the publication somehow?

**Comment by shayonj** [comment]
Yeah, it actually takes the account of tables during bootstrap, so there is a `--exclude_tables` to filter out tables early on from the publication. https://github.com/shayonj/pg_easy_replicate?tab=readme-ov-file#exclude-tables-from-replication

I do the like the idea of pg_easy_replicate using the publication as a source of truth however
