### ISSUE TITLE
stop_sync should pause replication, not drop it

### ISSUE THREAD

**Issue by jglien** [shayonj/pg_easy_replicate#55]
Currently, stop_sync drops the pub/sub, rather than pausing it. It would be preferable to have this command pause replication (disable pub/sub), rather than reset it. Perhaps dropping pub/sub could be moved to the cleanup command.

Then, start_sync can resume the existing pub/sub or create it.

**Comment by shayonj** [comment]
Thats interesting, thanks for the report. I wonder if its instead better to introduce `pause-sync` flag/option to do exactly what you mentioned. 

Curious, whats the use case, if you are able to share. Thanks!

**Comment by shayonj** [comment]
Closing due to inacitivity, please feel free to reopen with any additional thoughts or feedback, when you have a chance too.
