### ISSUE TITLE
start_sync failing

### ISSUE THREAD

**Issue by liaden** [shayonj/pg_easy_replicate#67]
I am upgrading from PG12 and I initially was trying to upgrade to PG15.

The error message I am seeing:
```
ERROR: CREATE SUBSCRIPTION ... WITH (create_slot = true) cannot run inside a transaction block
```

I enabled extra logging with the `DEBUG=1` environment setting, and I can see that there we are not running the `Query` with a transaction. 

### Things I tried

I tried upgrading to PG 14 and PG 13 to see if there was an issue with postgres 15 creating the slot on postgres 12.

I tried using the [deferred slot approach from the postgres docs](https://www.postgresql.org/docs/current/logical-replication-subscription.html#LOGICAL-REPLICATION-SUBSCRIPTION-EXAMPLES-DEFERRED-SLOT):
1. Change `CREATE SUBSCRIPTION` to have `connect = false`.
2. Run `pg_create_logical_replication_slot` on the source db.
3. Run the `ALTER SUBSCRIPTION ... ENABLE`.
4. Run the `ALTER SUBSCRIPTION .. REFRESH PUBLICATION.

The `REFRESH PUBLICATION` failed with the same error message. 

### Questions:
1. Is this an issue that my source database version is too old? If so, what version of postgres is supported at minimum?
2. Is this an issue of a long outstanding transaction on the source database? I don't think so since I would expect an issue about locks expiring if so...
3. Any other ideas to consider or try?

**Comment by shayonj** [comment]
Interesting. Are you manually modifying the create subscription somehow? Curious about `create_slot = true`, since `start_sync` doesn't take additional params also.

**Comment by shayonj** [comment]
Closing due to inacitivity, please feel free to reopen with any additional thoughts or feedback, when you have a chance too.
