### ISSUE TITLE
Switchover fails because of timeout

### ISSUE THREAD

**Issue by TrueCarry** [shayonj/pg_easy_replicate#90]
After I ran `pg_easy_replicate switchover`, it failed on full vacuum because of timeouts. I've manually removed vacuum from code and switchover completed successfully. I think adding flag that allows to skip vacuum or increase timeouts could be helpful

**Comment by shayonj** [comment]
Thanks for the report! I think we can reset and restore timeouts before and after vacuum. Will look into it this weekend hopefully.

**Comment by shayonj** [comment]
https://github.com/shayonj/pg_easy_replicate/releases/tag/v0.2.3

Is now out with the changes. Thanks for the report!
